/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.simlang.scoping;

import fr.mleduc.simlang.scoping.AbstractSimLangScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class SimLangScopeProvider extends AbstractSimLangScopeProvider {
}
