/*
 * generated by Xtext 2.12.0
 */
package fr.mleduc.cherry.converter.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class Cherry1to2ProposalProvider extends AbstractCherry1to2ProposalProvider {
}
