/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.fsmwithmethods.scoping;

import fr.mleduc.fsmwithmethods.scoping.AbstractFsmWithMethodsScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class FsmWithMethodsScopeProvider extends AbstractFsmWithMethodsScopeProvider {
}
