/*
 * generated by Xtext 2.12.0
 */
package fr.mleduc.macros.language


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MacrosLangRuntimeModule extends AbstractMacrosLangRuntimeModule {
}
