/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.macros.language.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.mleduc.macros.language.MacrosLangRuntimeModule;
import fr.mleduc.macros.language.MacrosLangStandaloneSetup;
import fr.mleduc.macros.language.ide.MacrosLangIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MacrosLangIdeSetup extends MacrosLangStandaloneSetup {
  @Override
  public Injector createInjector() {
    MacrosLangRuntimeModule _macrosLangRuntimeModule = new MacrosLangRuntimeModule();
    MacrosLangIdeModule _macrosLangIdeModule = new MacrosLangIdeModule();
    return Guice.createInjector(Modules2.mixin(_macrosLangRuntimeModule, _macrosLangIdeModule));
  }
}
