/**
 * generated by Xtext 2.13.0
 */
package fr.mleduc.gpfl.sequence.scoping;

import fr.mleduc.gpfl.sequence.scoping.AbstractSequenceScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class SequenceScopeProvider extends AbstractSequenceScopeProvider {
}
