/*
 * generated by Xtext 2.12.0
 */
package fr.mleduc.fsm.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFsmScopeProvider extends DelegatingScopeProvider {
}
