/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.lambdafsm.lambdaFsm;

import fr.mleduc.fsm.fsm.FsmPackage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.mleduc.lambdafsm.lambdaFsm.LambdaFsmFactory
 * @model kind="package"
 * @generated
 */
public interface LambdaFsmPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "lambdaFsm";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.mleduc.fr/lambdafsm/LambdaFsm";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "lambdaFsm";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LambdaFsmPackage eINSTANCE = fr.mleduc.lambdafsm.lambdaFsm.impl.LambdaFsmPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.mleduc.lambdafsm.lambdaFsm.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.lambdafsm.lambdaFsm.impl.ParameterImpl
   * @see fr.mleduc.lambdafsm.lambdaFsm.impl.LambdaFsmPackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__NAME = 0;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.mleduc.lambdafsm.lambdaFsm.impl.MethodDefImpl <em>Method Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.lambdafsm.lambdaFsm.impl.MethodDefImpl
   * @see fr.mleduc.lambdafsm.lambdaFsm.impl.LambdaFsmPackageImpl#getMethodDef()
   * @generated
   */
  int METHOD_DEF = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DEF__NAME = FsmPackage.STATE__NAME;

  /**
   * The feature id for the '<em><b>Transitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DEF__TRANSITIONS = FsmPackage.STATE__TRANSITIONS;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DEF__PARAMS = FsmPackage.STATE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Stmts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DEF__STMTS = FsmPackage.STATE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Method Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DEF_FEATURE_COUNT = FsmPackage.STATE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.mleduc.lambdafsm.lambdaFsm.impl.MethodCallImpl <em>Method Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.lambdafsm.lambdaFsm.impl.MethodCallImpl
   * @see fr.mleduc.lambdafsm.lambdaFsm.impl.LambdaFsmPackageImpl#getMethodCall()
   * @generated
   */
  int METHOD_CALL = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_CALL__NAME = FsmPackage.STATE__NAME;

  /**
   * The feature id for the '<em><b>Transitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_CALL__TRANSITIONS = FsmPackage.STATE__TRANSITIONS;

  /**
   * The feature id for the '<em><b>Method</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_CALL__METHOD = FsmPackage.STATE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_CALL__PARAMS = FsmPackage.STATE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Method Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_CALL_FEATURE_COUNT = FsmPackage.STATE_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link fr.mleduc.lambdafsm.lambdaFsm.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see fr.mleduc.lambdafsm.lambdaFsm.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link fr.mleduc.lambdafsm.lambdaFsm.Parameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.mleduc.lambdafsm.lambdaFsm.Parameter#getName()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Name();

  /**
   * Returns the meta object for class '{@link fr.mleduc.lambdafsm.lambdaFsm.MethodDef <em>Method Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Method Def</em>'.
   * @see fr.mleduc.lambdafsm.lambdaFsm.MethodDef
   * @generated
   */
  EClass getMethodDef();

  /**
   * Returns the meta object for the containment reference list '{@link fr.mleduc.lambdafsm.lambdaFsm.MethodDef#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see fr.mleduc.lambdafsm.lambdaFsm.MethodDef#getParams()
   * @see #getMethodDef()
   * @generated
   */
  EReference getMethodDef_Params();

  /**
   * Returns the meta object for the containment reference list '{@link fr.mleduc.lambdafsm.lambdaFsm.MethodDef#getStmts <em>Stmts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Stmts</em>'.
   * @see fr.mleduc.lambdafsm.lambdaFsm.MethodDef#getStmts()
   * @see #getMethodDef()
   * @generated
   */
  EReference getMethodDef_Stmts();

  /**
   * Returns the meta object for class '{@link fr.mleduc.lambdafsm.lambdaFsm.MethodCall <em>Method Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Method Call</em>'.
   * @see fr.mleduc.lambdafsm.lambdaFsm.MethodCall
   * @generated
   */
  EClass getMethodCall();

  /**
   * Returns the meta object for the reference '{@link fr.mleduc.lambdafsm.lambdaFsm.MethodCall#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Method</em>'.
   * @see fr.mleduc.lambdafsm.lambdaFsm.MethodCall#getMethod()
   * @see #getMethodCall()
   * @generated
   */
  EReference getMethodCall_Method();

  /**
   * Returns the meta object for the containment reference list '{@link fr.mleduc.lambdafsm.lambdaFsm.MethodCall#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see fr.mleduc.lambdafsm.lambdaFsm.MethodCall#getParams()
   * @see #getMethodCall()
   * @generated
   */
  EReference getMethodCall_Params();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  LambdaFsmFactory getLambdaFsmFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.mleduc.lambdafsm.lambdaFsm.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.lambdafsm.lambdaFsm.impl.ParameterImpl
     * @see fr.mleduc.lambdafsm.lambdaFsm.impl.LambdaFsmPackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__NAME = eINSTANCE.getParameter_Name();

    /**
     * The meta object literal for the '{@link fr.mleduc.lambdafsm.lambdaFsm.impl.MethodDefImpl <em>Method Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.lambdafsm.lambdaFsm.impl.MethodDefImpl
     * @see fr.mleduc.lambdafsm.lambdaFsm.impl.LambdaFsmPackageImpl#getMethodDef()
     * @generated
     */
    EClass METHOD_DEF = eINSTANCE.getMethodDef();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD_DEF__PARAMS = eINSTANCE.getMethodDef_Params();

    /**
     * The meta object literal for the '<em><b>Stmts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD_DEF__STMTS = eINSTANCE.getMethodDef_Stmts();

    /**
     * The meta object literal for the '{@link fr.mleduc.lambdafsm.lambdaFsm.impl.MethodCallImpl <em>Method Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.lambdafsm.lambdaFsm.impl.MethodCallImpl
     * @see fr.mleduc.lambdafsm.lambdaFsm.impl.LambdaFsmPackageImpl#getMethodCall()
     * @generated
     */
    EClass METHOD_CALL = eINSTANCE.getMethodCall();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD_CALL__METHOD = eINSTANCE.getMethodCall_Method();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD_CALL__PARAMS = eINSTANCE.getMethodCall_Params();

  }

} //LambdaFsmPackage
