/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.lambdafsm.scoping;

import fr.mleduc.lambdafsm.scoping.AbstractLambdaFsmScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class LambdaFsmScopeProvider extends AbstractLambdaFsmScopeProvider {
}
