/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.fsmwithmethods.tests;

import com.google.inject.Inject;
import fr.mleduc.fsmwithmethods.fsmWithMethods.Fsm;
import fr.mleduc.fsmwithmethods.tests.FsmWithMethodsInjectorProvider;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(FsmWithMethodsInjectorProvider.class)
@SuppressWarnings("all")
public class FsmWithMethodsParsingTest {
  @Inject
  private ParseHelper<Fsm> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final Fsm result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
      Assert.assertTrue(result.eResource().getErrors().isEmpty());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
