/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.macros.language.ui.contentassist;

import fr.mleduc.macros.language.ui.contentassist.AbstractMacrosLangProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MacrosLangProposalProvider extends AbstractMacrosLangProposalProvider {
}
