/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.fsmwithmethods.fsmWithMethods;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FExpression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.mleduc.fsmwithmethods.fsmWithMethods.FExpression#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see fr.mleduc.fsmwithmethods.fsmWithMethods.FsmWithMethodsPackage#getFExpression()
 * @model
 * @generated
 */
public interface FExpression extends Referentiable
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.mleduc.fsmwithmethods.fsmWithMethods.FsmWithMethodsPackage#getFExpression_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.mleduc.fsmwithmethods.fsmWithMethods.FExpression#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // FExpression
