/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.fsmwithmethods.fsmWithMethods;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fsm</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.mleduc.fsmwithmethods.fsmWithMethods.Fsm#getName <em>Name</em>}</li>
 *   <li>{@link fr.mleduc.fsmwithmethods.fsmWithMethods.Fsm#getState <em>State</em>}</li>
 *   <li>{@link fr.mleduc.fsmwithmethods.fsmWithMethods.Fsm#getExpressions <em>Expressions</em>}</li>
 * </ul>
 *
 * @see fr.mleduc.fsmwithmethods.fsmWithMethods.FsmWithMethodsPackage#getFsm()
 * @model
 * @generated
 */
public interface Fsm extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.mleduc.fsmwithmethods.fsmWithMethods.FsmWithMethodsPackage#getFsm_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.mleduc.fsmwithmethods.fsmWithMethods.Fsm#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>State</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>State</em>' reference.
   * @see #setState(State)
   * @see fr.mleduc.fsmwithmethods.fsmWithMethods.FsmWithMethodsPackage#getFsm_State()
   * @model
   * @generated
   */
  State getState();

  /**
   * Sets the value of the '{@link fr.mleduc.fsmwithmethods.fsmWithMethods.Fsm#getState <em>State</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State</em>' reference.
   * @see #getState()
   * @generated
   */
  void setState(State value);

  /**
   * Returns the value of the '<em><b>Expressions</b></em>' containment reference list.
   * The list contents are of type {@link fr.mleduc.fsmwithmethods.fsmWithMethods.FExpression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expressions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressions</em>' containment reference list.
   * @see fr.mleduc.fsmwithmethods.fsmWithMethods.FsmWithMethodsPackage#getFsm_Expressions()
   * @model containment="true"
   * @generated
   */
  EList<FExpression> getExpressions();

} // Fsm
