/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.fsmwithmethods.fsmWithMethods;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Referentiable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.mleduc.fsmwithmethods.fsmWithMethods.FsmWithMethodsPackage#getReferentiable()
 * @model
 * @generated
 */
public interface Referentiable extends EObject
{
} // Referentiable
