/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.fsmwithmethods.fsmWithMethods;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.mleduc.fsmwithmethods.fsmWithMethods.Transition#getEvent <em>Event</em>}</li>
 *   <li>{@link fr.mleduc.fsmwithmethods.fsmWithMethods.Transition#getFrom <em>From</em>}</li>
 *   <li>{@link fr.mleduc.fsmwithmethods.fsmWithMethods.Transition#getTo <em>To</em>}</li>
 * </ul>
 *
 * @see fr.mleduc.fsmwithmethods.fsmWithMethods.FsmWithMethodsPackage#getTransition()
 * @model
 * @generated
 */
public interface Transition extends FExpression
{
  /**
   * Returns the value of the '<em><b>Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Event</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event</em>' reference.
   * @see #setEvent(FExpression)
   * @see fr.mleduc.fsmwithmethods.fsmWithMethods.FsmWithMethodsPackage#getTransition_Event()
   * @model
   * @generated
   */
  FExpression getEvent();

  /**
   * Sets the value of the '{@link fr.mleduc.fsmwithmethods.fsmWithMethods.Transition#getEvent <em>Event</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event</em>' reference.
   * @see #getEvent()
   * @generated
   */
  void setEvent(FExpression value);

  /**
   * Returns the value of the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>From</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' reference.
   * @see #setFrom(FExpression)
   * @see fr.mleduc.fsmwithmethods.fsmWithMethods.FsmWithMethodsPackage#getTransition_From()
   * @model
   * @generated
   */
  FExpression getFrom();

  /**
   * Sets the value of the '{@link fr.mleduc.fsmwithmethods.fsmWithMethods.Transition#getFrom <em>From</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' reference.
   * @see #getFrom()
   * @generated
   */
  void setFrom(FExpression value);

  /**
   * Returns the value of the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>To</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' reference.
   * @see #setTo(FExpression)
   * @see fr.mleduc.fsmwithmethods.fsmWithMethods.FsmWithMethodsPackage#getTransition_To()
   * @model
   * @generated
   */
  FExpression getTo();

  /**
   * Sets the value of the '{@link fr.mleduc.fsmwithmethods.fsmWithMethods.Transition#getTo <em>To</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' reference.
   * @see #getTo()
   * @generated
   */
  void setTo(FExpression value);

} // Transition
