/*
 * generated by Xtext 2.12.0
 */
package fr.mleduc.fsmwithmethods.parser.antlr;

import com.google.inject.Inject;
import fr.mleduc.fsmwithmethods.parser.antlr.internal.InternalFsmWithMethodsParser;
import fr.mleduc.fsmwithmethods.services.FsmWithMethodsGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class FsmWithMethodsParser extends AbstractAntlrParser {

	@Inject
	private FsmWithMethodsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFsmWithMethodsParser createParser(XtextTokenStream stream) {
		return new InternalFsmWithMethodsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Fsm";
	}

	public FsmWithMethodsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FsmWithMethodsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
