/*
 * generated by Xtext 2.12.0
 */
package fr.mleduc.fsmwithmethods.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FsmWithMethodsAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/mleduc/fsmwithmethods/parser/antlr/internal/InternalFsmWithMethods.tokens");
	}
}
