/**
 * generated by Xtext 2.13.0
 */
package fr.mleduc.lambda;

import fr.mleduc.lambda.LambdaStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class LambdaStandaloneSetup extends LambdaStandaloneSetupGenerated {
  public static void doSetup() {
    new LambdaStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
