/*
 * generated by Xtext 2.12.0
 */
package fr.mleduc.cherry.converter.ui.tests;

import com.google.inject.Injector;
import fr.mleduc.cherry.converter.ui.internal.ConverterActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class Cherry1to2UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ConverterActivator.getInstance().getInjector("fr.mleduc.cherry.converter.Cherry1to2");
	}

}
