/*
 * generated by Xtext 2.13.0
 */
package fr.mleduc.gpfl.sequence.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SequenceAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/mleduc/gpfl/sequence/parser/antlr/internal/InternalSequence.tokens");
	}
}
