/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.gpfl.gpfl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Accept Cmd</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.mleduc.gpfl.gpfl.GpflPackage#getAcceptCmd()
 * @model
 * @generated
 */
public interface AcceptCmd extends GExpression
{
} // AcceptCmd
