/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.gpfl.gpfl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.mleduc.gpfl.gpfl.GpflFactory
 * @model kind="package"
 * @generated
 */
public interface GpflPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "gpfl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.mleduc.fr/gpfl/Gpfl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "gpfl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GpflPackage eINSTANCE = fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.ProgramImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__NAME = 0;

  /**
   * The feature id for the '<em><b>Automatas</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__AUTOMATAS = 1;

  /**
   * The feature id for the '<em><b>Init Stmts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__INIT_STMTS = 2;

  /**
   * The feature id for the '<em><b>Stmts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__STMTS = 3;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.GExpressionImpl <em>GExpression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.GExpressionImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getGExpression()
   * @generated
   */
  int GEXPRESSION = 1;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GEXPRESSION__EXPRESSION = 0;

  /**
   * The number of structural features of the '<em>GExpression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GEXPRESSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.FieldImpl <em>Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.FieldImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getField()
   * @generated
   */
  int FIELD = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__VALUE = 1;

  /**
   * The number of structural features of the '<em>Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.AutomataDefImpl <em>Automata Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.AutomataDefImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getAutomataDef()
   * @generated
   */
  int AUTOMATA_DEF = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTOMATA_DEF__NAME = 0;

  /**
   * The feature id for the '<em><b>Init</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTOMATA_DEF__INIT = 1;

  /**
   * The feature id for the '<em><b>States</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTOMATA_DEF__STATES = 2;

  /**
   * The number of structural features of the '<em>Automata Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTOMATA_DEF_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.StateImpl <em>State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.StateImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getState()
   * @generated
   */
  int STATE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__NAME = 0;

  /**
   * The feature id for the '<em><b>Transitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__TRANSITIONS = 1;

  /**
   * The number of structural features of the '<em>State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.TransitionImpl <em>Transition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.TransitionImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getTransition()
   * @generated
   */
  int TRANSITION = 5;

  /**
   * The feature id for the '<em><b>Event</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__EVENT = 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__TARGET = 1;

  /**
   * The number of structural features of the '<em>Transition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.CondStmtImpl <em>Cond Stmt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.CondStmtImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getCondStmt()
   * @generated
   */
  int COND_STMT = 6;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COND_STMT__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COND_STMT__EXP = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Stmts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COND_STMT__STMTS = GEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Cond Stmt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COND_STMT_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.IterStmtImpl <em>Iter Stmt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.IterStmtImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getIterStmt()
   * @generated
   */
  int ITER_STMT = 7;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITER_STMT__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITER_STMT__EXP = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Stmts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITER_STMT__STMTS = GEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Iter Stmt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITER_STMT_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.InterruptStmtImpl <em>Interrupt Stmt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.InterruptStmtImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getInterruptStmt()
   * @generated
   */
  int INTERRUPT_STMT = 8;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERRUPT_STMT__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Timeout</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERRUPT_STMT__TIMEOUT = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Periodic</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERRUPT_STMT__PERIODIC = GEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Stmts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERRUPT_STMT__STMTS = GEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Interrupt Stmt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERRUPT_STMT_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.NopCmdImpl <em>Nop Cmd</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.NopCmdImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getNopCmd()
   * @generated
   */
  int NOP_CMD = 9;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOP_CMD__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The number of structural features of the '<em>Nop Cmd</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOP_CMD_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.AcceptCmdImpl <em>Accept Cmd</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.AcceptCmdImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getAcceptCmd()
   * @generated
   */
  int ACCEPT_CMD = 10;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACCEPT_CMD__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The number of structural features of the '<em>Accept Cmd</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACCEPT_CMD_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.DropCmdImpl <em>Drop Cmd</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.DropCmdImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getDropCmd()
   * @generated
   */
  int DROP_CMD = 11;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROP_CMD__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The number of structural features of the '<em>Drop Cmd</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROP_CMD_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.SendCmdImpl <em>Send Cmd</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.SendCmdImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getSendCmd()
   * @generated
   */
  int SEND_CMD = 12;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEND_CMD__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Port</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEND_CMD__PORT = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEND_CMD__FIELDS = GEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Send Cmd</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEND_CMD_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.AlarmCmdImpl <em>Alarm Cmd</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.AlarmCmdImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getAlarmCmd()
   * @generated
   */
  int ALARM_CMD = 13;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALARM_CMD__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALARM_CMD__EXP = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Alarm Cmd</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALARM_CMD_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.SetCmdImpl <em>Set Cmd</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.SetCmdImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getSetCmd()
   * @generated
   */
  int SET_CMD = 14;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET_CMD__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET_CMD__NAME = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET_CMD__EXP = GEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Set Cmd</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET_CMD_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.AutomatonCmdImpl <em>Automaton Cmd</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.AutomatonCmdImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getAutomatonCmd()
   * @generated
   */
  int AUTOMATON_CMD = 15;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTOMATON_CMD__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTOMATON_CMD__NAME = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Automaton</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTOMATON_CMD__AUTOMATON = GEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Automaton Cmd</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTOMATON_CMD_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.StpCmdImpl <em>Stp Cmd</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.StpCmdImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getStpCmd()
   * @generated
   */
  int STP_CMD = 16;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STP_CMD__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Automaton</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STP_CMD__AUTOMATON = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Event</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STP_CMD__EVENT = GEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Errors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STP_CMD__ERRORS = GEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Stp Cmd</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STP_CMD_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.CmdAndImpl <em>Cmd And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.CmdAndImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getCmdAnd()
   * @generated
   */
  int CMD_AND = 17;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_AND__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_AND__LEFT = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_AND__RIGHT = GEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Cmd And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_AND_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.CmdEqImpl <em>Cmd Eq</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.CmdEqImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getCmdEq()
   * @generated
   */
  int CMD_EQ = 18;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_EQ__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_EQ__LEFT = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_EQ__RIGHT = GEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Cmd Eq</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_EQ_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.CmdNEqImpl <em>Cmd NEq</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.CmdNEqImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getCmdNEq()
   * @generated
   */
  int CMD_NEQ = 19;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_NEQ__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_NEQ__LEFT = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_NEQ__RIGHT = GEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Cmd NEq</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_NEQ_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.CmdGECompareImpl <em>Cmd GE Compare</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.CmdGECompareImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getCmdGECompare()
   * @generated
   */
  int CMD_GE_COMPARE = 20;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_GE_COMPARE__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_GE_COMPARE__LEFT = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_GE_COMPARE__RIGHT = GEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Cmd GE Compare</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_GE_COMPARE_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.CmdLECompareImpl <em>Cmd LE Compare</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.CmdLECompareImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getCmdLECompare()
   * @generated
   */
  int CMD_LE_COMPARE = 21;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_LE_COMPARE__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_LE_COMPARE__LEFT = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_LE_COMPARE__RIGHT = GEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Cmd LE Compare</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_LE_COMPARE_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.CmdGCompareImpl <em>Cmd GCompare</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.CmdGCompareImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getCmdGCompare()
   * @generated
   */
  int CMD_GCOMPARE = 22;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_GCOMPARE__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_GCOMPARE__LEFT = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_GCOMPARE__RIGHT = GEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Cmd GCompare</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_GCOMPARE_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.CmdLCompareImpl <em>Cmd LCompare</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.CmdLCompareImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getCmdLCompare()
   * @generated
   */
  int CMD_LCOMPARE = 23;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_LCOMPARE__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_LCOMPARE__LEFT = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_LCOMPARE__RIGHT = GEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Cmd LCompare</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_LCOMPARE_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.CmdAddImpl <em>Cmd Add</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.CmdAddImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getCmdAdd()
   * @generated
   */
  int CMD_ADD = 24;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_ADD__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_ADD__LEFT = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_ADD__RIGHT = GEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Cmd Add</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_ADD_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.CmdSubImpl <em>Cmd Sub</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.CmdSubImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getCmdSub()
   * @generated
   */
  int CMD_SUB = 25;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_SUB__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_SUB__LEFT = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_SUB__RIGHT = GEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Cmd Sub</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_SUB_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.IntLitCmdImpl <em>Int Lit Cmd</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.IntLitCmdImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getIntLitCmd()
   * @generated
   */
  int INT_LIT_CMD = 26;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LIT_CMD__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LIT_CMD__VALUE = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Lit Cmd</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LIT_CMD_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.GBoolTrueImpl <em>GBool True</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.GBoolTrueImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getGBoolTrue()
   * @generated
   */
  int GBOOL_TRUE = 27;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GBOOL_TRUE__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The number of structural features of the '<em>GBool True</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GBOOL_TRUE_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.GBoolFalseImpl <em>GBool False</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.GBoolFalseImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getGBoolFalse()
   * @generated
   */
  int GBOOL_FALSE = 28;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GBOOL_FALSE__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The number of structural features of the '<em>GBool False</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GBOOL_FALSE_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.StringLitImpl <em>String Lit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.StringLitImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getStringLit()
   * @generated
   */
  int STRING_LIT = 29;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LIT__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LIT__VALUE = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Lit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LIT_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.VariableImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 30;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__VALUE = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.PortLitImpl <em>Port Lit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.PortLitImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getPortLit()
   * @generated
   */
  int PORT_LIT = 31;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_LIT__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The feature id for the '<em><b>In Side</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_LIT__IN_SIDE = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Port Lit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_LIT_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.InPortImpl <em>In Port</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.InPortImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getInPort()
   * @generated
   */
  int IN_PORT = 32;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IN_PORT__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The number of structural features of the '<em>In Port</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IN_PORT_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.mleduc.gpfl.gpfl.impl.OutPortImpl <em>Out Port</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.gpfl.gpfl.impl.OutPortImpl
   * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getOutPort()
   * @generated
   */
  int OUT_PORT = 33;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUT_PORT__EXPRESSION = GEXPRESSION__EXPRESSION;

  /**
   * The number of structural features of the '<em>Out Port</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUT_PORT_FEATURE_COUNT = GEXPRESSION_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see fr.mleduc.gpfl.gpfl.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the attribute '{@link fr.mleduc.gpfl.gpfl.Program#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.mleduc.gpfl.gpfl.Program#getName()
   * @see #getProgram()
   * @generated
   */
  EAttribute getProgram_Name();

  /**
   * Returns the meta object for the containment reference list '{@link fr.mleduc.gpfl.gpfl.Program#getAutomatas <em>Automatas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Automatas</em>'.
   * @see fr.mleduc.gpfl.gpfl.Program#getAutomatas()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Automatas();

  /**
   * Returns the meta object for the containment reference list '{@link fr.mleduc.gpfl.gpfl.Program#getInitStmts <em>Init Stmts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Init Stmts</em>'.
   * @see fr.mleduc.gpfl.gpfl.Program#getInitStmts()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_InitStmts();

  /**
   * Returns the meta object for the containment reference list '{@link fr.mleduc.gpfl.gpfl.Program#getStmts <em>Stmts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Stmts</em>'.
   * @see fr.mleduc.gpfl.gpfl.Program#getStmts()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Stmts();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.GExpression <em>GExpression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>GExpression</em>'.
   * @see fr.mleduc.gpfl.gpfl.GExpression
   * @generated
   */
  EClass getGExpression();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.GExpression#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see fr.mleduc.gpfl.gpfl.GExpression#getExpression()
   * @see #getGExpression()
   * @generated
   */
  EReference getGExpression_Expression();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.Field <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Field</em>'.
   * @see fr.mleduc.gpfl.gpfl.Field
   * @generated
   */
  EClass getField();

  /**
   * Returns the meta object for the attribute '{@link fr.mleduc.gpfl.gpfl.Field#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.mleduc.gpfl.gpfl.Field#getName()
   * @see #getField()
   * @generated
   */
  EAttribute getField_Name();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.Field#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see fr.mleduc.gpfl.gpfl.Field#getValue()
   * @see #getField()
   * @generated
   */
  EReference getField_Value();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.AutomataDef <em>Automata Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Automata Def</em>'.
   * @see fr.mleduc.gpfl.gpfl.AutomataDef
   * @generated
   */
  EClass getAutomataDef();

  /**
   * Returns the meta object for the attribute '{@link fr.mleduc.gpfl.gpfl.AutomataDef#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.mleduc.gpfl.gpfl.AutomataDef#getName()
   * @see #getAutomataDef()
   * @generated
   */
  EAttribute getAutomataDef_Name();

  /**
   * Returns the meta object for the reference '{@link fr.mleduc.gpfl.gpfl.AutomataDef#getInit <em>Init</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Init</em>'.
   * @see fr.mleduc.gpfl.gpfl.AutomataDef#getInit()
   * @see #getAutomataDef()
   * @generated
   */
  EReference getAutomataDef_Init();

  /**
   * Returns the meta object for the containment reference list '{@link fr.mleduc.gpfl.gpfl.AutomataDef#getStates <em>States</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>States</em>'.
   * @see fr.mleduc.gpfl.gpfl.AutomataDef#getStates()
   * @see #getAutomataDef()
   * @generated
   */
  EReference getAutomataDef_States();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.State <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State</em>'.
   * @see fr.mleduc.gpfl.gpfl.State
   * @generated
   */
  EClass getState();

  /**
   * Returns the meta object for the attribute '{@link fr.mleduc.gpfl.gpfl.State#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.mleduc.gpfl.gpfl.State#getName()
   * @see #getState()
   * @generated
   */
  EAttribute getState_Name();

  /**
   * Returns the meta object for the containment reference list '{@link fr.mleduc.gpfl.gpfl.State#getTransitions <em>Transitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Transitions</em>'.
   * @see fr.mleduc.gpfl.gpfl.State#getTransitions()
   * @see #getState()
   * @generated
   */
  EReference getState_Transitions();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.Transition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transition</em>'.
   * @see fr.mleduc.gpfl.gpfl.Transition
   * @generated
   */
  EClass getTransition();

  /**
   * Returns the meta object for the attribute '{@link fr.mleduc.gpfl.gpfl.Transition#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Event</em>'.
   * @see fr.mleduc.gpfl.gpfl.Transition#getEvent()
   * @see #getTransition()
   * @generated
   */
  EAttribute getTransition_Event();

  /**
   * Returns the meta object for the reference '{@link fr.mleduc.gpfl.gpfl.Transition#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see fr.mleduc.gpfl.gpfl.Transition#getTarget()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Target();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.CondStmt <em>Cond Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cond Stmt</em>'.
   * @see fr.mleduc.gpfl.gpfl.CondStmt
   * @generated
   */
  EClass getCondStmt();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.CondStmt#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see fr.mleduc.gpfl.gpfl.CondStmt#getExp()
   * @see #getCondStmt()
   * @generated
   */
  EReference getCondStmt_Exp();

  /**
   * Returns the meta object for the containment reference list '{@link fr.mleduc.gpfl.gpfl.CondStmt#getStmts <em>Stmts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Stmts</em>'.
   * @see fr.mleduc.gpfl.gpfl.CondStmt#getStmts()
   * @see #getCondStmt()
   * @generated
   */
  EReference getCondStmt_Stmts();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.IterStmt <em>Iter Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Iter Stmt</em>'.
   * @see fr.mleduc.gpfl.gpfl.IterStmt
   * @generated
   */
  EClass getIterStmt();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.IterStmt#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see fr.mleduc.gpfl.gpfl.IterStmt#getExp()
   * @see #getIterStmt()
   * @generated
   */
  EReference getIterStmt_Exp();

  /**
   * Returns the meta object for the containment reference list '{@link fr.mleduc.gpfl.gpfl.IterStmt#getStmts <em>Stmts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Stmts</em>'.
   * @see fr.mleduc.gpfl.gpfl.IterStmt#getStmts()
   * @see #getIterStmt()
   * @generated
   */
  EReference getIterStmt_Stmts();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.InterruptStmt <em>Interrupt Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Interrupt Stmt</em>'.
   * @see fr.mleduc.gpfl.gpfl.InterruptStmt
   * @generated
   */
  EClass getInterruptStmt();

  /**
   * Returns the meta object for the attribute '{@link fr.mleduc.gpfl.gpfl.InterruptStmt#getTimeout <em>Timeout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Timeout</em>'.
   * @see fr.mleduc.gpfl.gpfl.InterruptStmt#getTimeout()
   * @see #getInterruptStmt()
   * @generated
   */
  EAttribute getInterruptStmt_Timeout();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.InterruptStmt#getPeriodic <em>Periodic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Periodic</em>'.
   * @see fr.mleduc.gpfl.gpfl.InterruptStmt#getPeriodic()
   * @see #getInterruptStmt()
   * @generated
   */
  EReference getInterruptStmt_Periodic();

  /**
   * Returns the meta object for the containment reference list '{@link fr.mleduc.gpfl.gpfl.InterruptStmt#getStmts <em>Stmts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Stmts</em>'.
   * @see fr.mleduc.gpfl.gpfl.InterruptStmt#getStmts()
   * @see #getInterruptStmt()
   * @generated
   */
  EReference getInterruptStmt_Stmts();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.NopCmd <em>Nop Cmd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nop Cmd</em>'.
   * @see fr.mleduc.gpfl.gpfl.NopCmd
   * @generated
   */
  EClass getNopCmd();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.AcceptCmd <em>Accept Cmd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Accept Cmd</em>'.
   * @see fr.mleduc.gpfl.gpfl.AcceptCmd
   * @generated
   */
  EClass getAcceptCmd();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.DropCmd <em>Drop Cmd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Drop Cmd</em>'.
   * @see fr.mleduc.gpfl.gpfl.DropCmd
   * @generated
   */
  EClass getDropCmd();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.SendCmd <em>Send Cmd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Send Cmd</em>'.
   * @see fr.mleduc.gpfl.gpfl.SendCmd
   * @generated
   */
  EClass getSendCmd();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.SendCmd#getPort <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Port</em>'.
   * @see fr.mleduc.gpfl.gpfl.SendCmd#getPort()
   * @see #getSendCmd()
   * @generated
   */
  EReference getSendCmd_Port();

  /**
   * Returns the meta object for the containment reference list '{@link fr.mleduc.gpfl.gpfl.SendCmd#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fields</em>'.
   * @see fr.mleduc.gpfl.gpfl.SendCmd#getFields()
   * @see #getSendCmd()
   * @generated
   */
  EReference getSendCmd_Fields();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.AlarmCmd <em>Alarm Cmd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Alarm Cmd</em>'.
   * @see fr.mleduc.gpfl.gpfl.AlarmCmd
   * @generated
   */
  EClass getAlarmCmd();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.AlarmCmd#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see fr.mleduc.gpfl.gpfl.AlarmCmd#getExp()
   * @see #getAlarmCmd()
   * @generated
   */
  EReference getAlarmCmd_Exp();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.SetCmd <em>Set Cmd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Set Cmd</em>'.
   * @see fr.mleduc.gpfl.gpfl.SetCmd
   * @generated
   */
  EClass getSetCmd();

  /**
   * Returns the meta object for the attribute '{@link fr.mleduc.gpfl.gpfl.SetCmd#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.mleduc.gpfl.gpfl.SetCmd#getName()
   * @see #getSetCmd()
   * @generated
   */
  EAttribute getSetCmd_Name();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.SetCmd#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see fr.mleduc.gpfl.gpfl.SetCmd#getExp()
   * @see #getSetCmd()
   * @generated
   */
  EReference getSetCmd_Exp();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.AutomatonCmd <em>Automaton Cmd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Automaton Cmd</em>'.
   * @see fr.mleduc.gpfl.gpfl.AutomatonCmd
   * @generated
   */
  EClass getAutomatonCmd();

  /**
   * Returns the meta object for the attribute '{@link fr.mleduc.gpfl.gpfl.AutomatonCmd#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.mleduc.gpfl.gpfl.AutomatonCmd#getName()
   * @see #getAutomatonCmd()
   * @generated
   */
  EAttribute getAutomatonCmd_Name();

  /**
   * Returns the meta object for the reference '{@link fr.mleduc.gpfl.gpfl.AutomatonCmd#getAutomaton <em>Automaton</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Automaton</em>'.
   * @see fr.mleduc.gpfl.gpfl.AutomatonCmd#getAutomaton()
   * @see #getAutomatonCmd()
   * @generated
   */
  EReference getAutomatonCmd_Automaton();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.StpCmd <em>Stp Cmd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stp Cmd</em>'.
   * @see fr.mleduc.gpfl.gpfl.StpCmd
   * @generated
   */
  EClass getStpCmd();

  /**
   * Returns the meta object for the reference '{@link fr.mleduc.gpfl.gpfl.StpCmd#getAutomaton <em>Automaton</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Automaton</em>'.
   * @see fr.mleduc.gpfl.gpfl.StpCmd#getAutomaton()
   * @see #getStpCmd()
   * @generated
   */
  EReference getStpCmd_Automaton();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.StpCmd#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Event</em>'.
   * @see fr.mleduc.gpfl.gpfl.StpCmd#getEvent()
   * @see #getStpCmd()
   * @generated
   */
  EReference getStpCmd_Event();

  /**
   * Returns the meta object for the containment reference list '{@link fr.mleduc.gpfl.gpfl.StpCmd#getErrors <em>Errors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Errors</em>'.
   * @see fr.mleduc.gpfl.gpfl.StpCmd#getErrors()
   * @see #getStpCmd()
   * @generated
   */
  EReference getStpCmd_Errors();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.CmdAnd <em>Cmd And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cmd And</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdAnd
   * @generated
   */
  EClass getCmdAnd();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.CmdAnd#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdAnd#getLeft()
   * @see #getCmdAnd()
   * @generated
   */
  EReference getCmdAnd_Left();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.CmdAnd#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdAnd#getRight()
   * @see #getCmdAnd()
   * @generated
   */
  EReference getCmdAnd_Right();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.CmdEq <em>Cmd Eq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cmd Eq</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdEq
   * @generated
   */
  EClass getCmdEq();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.CmdEq#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdEq#getLeft()
   * @see #getCmdEq()
   * @generated
   */
  EReference getCmdEq_Left();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.CmdEq#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdEq#getRight()
   * @see #getCmdEq()
   * @generated
   */
  EReference getCmdEq_Right();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.CmdNEq <em>Cmd NEq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cmd NEq</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdNEq
   * @generated
   */
  EClass getCmdNEq();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.CmdNEq#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdNEq#getLeft()
   * @see #getCmdNEq()
   * @generated
   */
  EReference getCmdNEq_Left();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.CmdNEq#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdNEq#getRight()
   * @see #getCmdNEq()
   * @generated
   */
  EReference getCmdNEq_Right();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.CmdGECompare <em>Cmd GE Compare</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cmd GE Compare</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdGECompare
   * @generated
   */
  EClass getCmdGECompare();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.CmdGECompare#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdGECompare#getLeft()
   * @see #getCmdGECompare()
   * @generated
   */
  EReference getCmdGECompare_Left();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.CmdGECompare#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdGECompare#getRight()
   * @see #getCmdGECompare()
   * @generated
   */
  EReference getCmdGECompare_Right();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.CmdLECompare <em>Cmd LE Compare</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cmd LE Compare</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdLECompare
   * @generated
   */
  EClass getCmdLECompare();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.CmdLECompare#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdLECompare#getLeft()
   * @see #getCmdLECompare()
   * @generated
   */
  EReference getCmdLECompare_Left();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.CmdLECompare#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdLECompare#getRight()
   * @see #getCmdLECompare()
   * @generated
   */
  EReference getCmdLECompare_Right();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.CmdGCompare <em>Cmd GCompare</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cmd GCompare</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdGCompare
   * @generated
   */
  EClass getCmdGCompare();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.CmdGCompare#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdGCompare#getLeft()
   * @see #getCmdGCompare()
   * @generated
   */
  EReference getCmdGCompare_Left();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.CmdGCompare#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdGCompare#getRight()
   * @see #getCmdGCompare()
   * @generated
   */
  EReference getCmdGCompare_Right();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.CmdLCompare <em>Cmd LCompare</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cmd LCompare</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdLCompare
   * @generated
   */
  EClass getCmdLCompare();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.CmdLCompare#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdLCompare#getLeft()
   * @see #getCmdLCompare()
   * @generated
   */
  EReference getCmdLCompare_Left();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.CmdLCompare#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdLCompare#getRight()
   * @see #getCmdLCompare()
   * @generated
   */
  EReference getCmdLCompare_Right();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.CmdAdd <em>Cmd Add</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cmd Add</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdAdd
   * @generated
   */
  EClass getCmdAdd();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.CmdAdd#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdAdd#getLeft()
   * @see #getCmdAdd()
   * @generated
   */
  EReference getCmdAdd_Left();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.CmdAdd#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdAdd#getRight()
   * @see #getCmdAdd()
   * @generated
   */
  EReference getCmdAdd_Right();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.CmdSub <em>Cmd Sub</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cmd Sub</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdSub
   * @generated
   */
  EClass getCmdSub();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.CmdSub#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdSub#getLeft()
   * @see #getCmdSub()
   * @generated
   */
  EReference getCmdSub_Left();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.gpfl.gpfl.CmdSub#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see fr.mleduc.gpfl.gpfl.CmdSub#getRight()
   * @see #getCmdSub()
   * @generated
   */
  EReference getCmdSub_Right();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.IntLitCmd <em>Int Lit Cmd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Lit Cmd</em>'.
   * @see fr.mleduc.gpfl.gpfl.IntLitCmd
   * @generated
   */
  EClass getIntLitCmd();

  /**
   * Returns the meta object for the attribute '{@link fr.mleduc.gpfl.gpfl.IntLitCmd#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see fr.mleduc.gpfl.gpfl.IntLitCmd#getValue()
   * @see #getIntLitCmd()
   * @generated
   */
  EAttribute getIntLitCmd_Value();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.GBoolTrue <em>GBool True</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>GBool True</em>'.
   * @see fr.mleduc.gpfl.gpfl.GBoolTrue
   * @generated
   */
  EClass getGBoolTrue();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.GBoolFalse <em>GBool False</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>GBool False</em>'.
   * @see fr.mleduc.gpfl.gpfl.GBoolFalse
   * @generated
   */
  EClass getGBoolFalse();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.StringLit <em>String Lit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Lit</em>'.
   * @see fr.mleduc.gpfl.gpfl.StringLit
   * @generated
   */
  EClass getStringLit();

  /**
   * Returns the meta object for the attribute '{@link fr.mleduc.gpfl.gpfl.StringLit#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see fr.mleduc.gpfl.gpfl.StringLit#getValue()
   * @see #getStringLit()
   * @generated
   */
  EAttribute getStringLit_Value();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see fr.mleduc.gpfl.gpfl.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link fr.mleduc.gpfl.gpfl.Variable#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see fr.mleduc.gpfl.gpfl.Variable#getValue()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Value();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.PortLit <em>Port Lit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Port Lit</em>'.
   * @see fr.mleduc.gpfl.gpfl.PortLit
   * @generated
   */
  EClass getPortLit();

  /**
   * Returns the meta object for the attribute '{@link fr.mleduc.gpfl.gpfl.PortLit#isInSide <em>In Side</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>In Side</em>'.
   * @see fr.mleduc.gpfl.gpfl.PortLit#isInSide()
   * @see #getPortLit()
   * @generated
   */
  EAttribute getPortLit_InSide();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.InPort <em>In Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>In Port</em>'.
   * @see fr.mleduc.gpfl.gpfl.InPort
   * @generated
   */
  EClass getInPort();

  /**
   * Returns the meta object for class '{@link fr.mleduc.gpfl.gpfl.OutPort <em>Out Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Out Port</em>'.
   * @see fr.mleduc.gpfl.gpfl.OutPort
   * @generated
   */
  EClass getOutPort();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GpflFactory getGpflFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.ProgramImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAM__NAME = eINSTANCE.getProgram_Name();

    /**
     * The meta object literal for the '<em><b>Automatas</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__AUTOMATAS = eINSTANCE.getProgram_Automatas();

    /**
     * The meta object literal for the '<em><b>Init Stmts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__INIT_STMTS = eINSTANCE.getProgram_InitStmts();

    /**
     * The meta object literal for the '<em><b>Stmts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__STMTS = eINSTANCE.getProgram_Stmts();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.GExpressionImpl <em>GExpression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.GExpressionImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getGExpression()
     * @generated
     */
    EClass GEXPRESSION = eINSTANCE.getGExpression();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GEXPRESSION__EXPRESSION = eINSTANCE.getGExpression_Expression();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.FieldImpl <em>Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.FieldImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getField()
     * @generated
     */
    EClass FIELD = eINSTANCE.getField();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD__NAME = eINSTANCE.getField_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD__VALUE = eINSTANCE.getField_Value();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.AutomataDefImpl <em>Automata Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.AutomataDefImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getAutomataDef()
     * @generated
     */
    EClass AUTOMATA_DEF = eINSTANCE.getAutomataDef();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AUTOMATA_DEF__NAME = eINSTANCE.getAutomataDef_Name();

    /**
     * The meta object literal for the '<em><b>Init</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AUTOMATA_DEF__INIT = eINSTANCE.getAutomataDef_Init();

    /**
     * The meta object literal for the '<em><b>States</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AUTOMATA_DEF__STATES = eINSTANCE.getAutomataDef_States();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.StateImpl <em>State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.StateImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getState()
     * @generated
     */
    EClass STATE = eINSTANCE.getState();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE__NAME = eINSTANCE.getState_Name();

    /**
     * The meta object literal for the '<em><b>Transitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__TRANSITIONS = eINSTANCE.getState_Transitions();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.TransitionImpl <em>Transition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.TransitionImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getTransition()
     * @generated
     */
    EClass TRANSITION = eINSTANCE.getTransition();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITION__EVENT = eINSTANCE.getTransition_Event();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__TARGET = eINSTANCE.getTransition_Target();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.CondStmtImpl <em>Cond Stmt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.CondStmtImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getCondStmt()
     * @generated
     */
    EClass COND_STMT = eINSTANCE.getCondStmt();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COND_STMT__EXP = eINSTANCE.getCondStmt_Exp();

    /**
     * The meta object literal for the '<em><b>Stmts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COND_STMT__STMTS = eINSTANCE.getCondStmt_Stmts();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.IterStmtImpl <em>Iter Stmt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.IterStmtImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getIterStmt()
     * @generated
     */
    EClass ITER_STMT = eINSTANCE.getIterStmt();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ITER_STMT__EXP = eINSTANCE.getIterStmt_Exp();

    /**
     * The meta object literal for the '<em><b>Stmts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ITER_STMT__STMTS = eINSTANCE.getIterStmt_Stmts();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.InterruptStmtImpl <em>Interrupt Stmt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.InterruptStmtImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getInterruptStmt()
     * @generated
     */
    EClass INTERRUPT_STMT = eINSTANCE.getInterruptStmt();

    /**
     * The meta object literal for the '<em><b>Timeout</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERRUPT_STMT__TIMEOUT = eINSTANCE.getInterruptStmt_Timeout();

    /**
     * The meta object literal for the '<em><b>Periodic</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERRUPT_STMT__PERIODIC = eINSTANCE.getInterruptStmt_Periodic();

    /**
     * The meta object literal for the '<em><b>Stmts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERRUPT_STMT__STMTS = eINSTANCE.getInterruptStmt_Stmts();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.NopCmdImpl <em>Nop Cmd</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.NopCmdImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getNopCmd()
     * @generated
     */
    EClass NOP_CMD = eINSTANCE.getNopCmd();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.AcceptCmdImpl <em>Accept Cmd</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.AcceptCmdImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getAcceptCmd()
     * @generated
     */
    EClass ACCEPT_CMD = eINSTANCE.getAcceptCmd();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.DropCmdImpl <em>Drop Cmd</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.DropCmdImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getDropCmd()
     * @generated
     */
    EClass DROP_CMD = eINSTANCE.getDropCmd();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.SendCmdImpl <em>Send Cmd</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.SendCmdImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getSendCmd()
     * @generated
     */
    EClass SEND_CMD = eINSTANCE.getSendCmd();

    /**
     * The meta object literal for the '<em><b>Port</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEND_CMD__PORT = eINSTANCE.getSendCmd_Port();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEND_CMD__FIELDS = eINSTANCE.getSendCmd_Fields();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.AlarmCmdImpl <em>Alarm Cmd</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.AlarmCmdImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getAlarmCmd()
     * @generated
     */
    EClass ALARM_CMD = eINSTANCE.getAlarmCmd();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALARM_CMD__EXP = eINSTANCE.getAlarmCmd_Exp();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.SetCmdImpl <em>Set Cmd</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.SetCmdImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getSetCmd()
     * @generated
     */
    EClass SET_CMD = eINSTANCE.getSetCmd();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SET_CMD__NAME = eINSTANCE.getSetCmd_Name();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SET_CMD__EXP = eINSTANCE.getSetCmd_Exp();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.AutomatonCmdImpl <em>Automaton Cmd</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.AutomatonCmdImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getAutomatonCmd()
     * @generated
     */
    EClass AUTOMATON_CMD = eINSTANCE.getAutomatonCmd();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AUTOMATON_CMD__NAME = eINSTANCE.getAutomatonCmd_Name();

    /**
     * The meta object literal for the '<em><b>Automaton</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AUTOMATON_CMD__AUTOMATON = eINSTANCE.getAutomatonCmd_Automaton();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.StpCmdImpl <em>Stp Cmd</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.StpCmdImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getStpCmd()
     * @generated
     */
    EClass STP_CMD = eINSTANCE.getStpCmd();

    /**
     * The meta object literal for the '<em><b>Automaton</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STP_CMD__AUTOMATON = eINSTANCE.getStpCmd_Automaton();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STP_CMD__EVENT = eINSTANCE.getStpCmd_Event();

    /**
     * The meta object literal for the '<em><b>Errors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STP_CMD__ERRORS = eINSTANCE.getStpCmd_Errors();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.CmdAndImpl <em>Cmd And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.CmdAndImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getCmdAnd()
     * @generated
     */
    EClass CMD_AND = eINSTANCE.getCmdAnd();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMD_AND__LEFT = eINSTANCE.getCmdAnd_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMD_AND__RIGHT = eINSTANCE.getCmdAnd_Right();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.CmdEqImpl <em>Cmd Eq</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.CmdEqImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getCmdEq()
     * @generated
     */
    EClass CMD_EQ = eINSTANCE.getCmdEq();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMD_EQ__LEFT = eINSTANCE.getCmdEq_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMD_EQ__RIGHT = eINSTANCE.getCmdEq_Right();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.CmdNEqImpl <em>Cmd NEq</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.CmdNEqImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getCmdNEq()
     * @generated
     */
    EClass CMD_NEQ = eINSTANCE.getCmdNEq();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMD_NEQ__LEFT = eINSTANCE.getCmdNEq_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMD_NEQ__RIGHT = eINSTANCE.getCmdNEq_Right();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.CmdGECompareImpl <em>Cmd GE Compare</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.CmdGECompareImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getCmdGECompare()
     * @generated
     */
    EClass CMD_GE_COMPARE = eINSTANCE.getCmdGECompare();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMD_GE_COMPARE__LEFT = eINSTANCE.getCmdGECompare_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMD_GE_COMPARE__RIGHT = eINSTANCE.getCmdGECompare_Right();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.CmdLECompareImpl <em>Cmd LE Compare</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.CmdLECompareImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getCmdLECompare()
     * @generated
     */
    EClass CMD_LE_COMPARE = eINSTANCE.getCmdLECompare();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMD_LE_COMPARE__LEFT = eINSTANCE.getCmdLECompare_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMD_LE_COMPARE__RIGHT = eINSTANCE.getCmdLECompare_Right();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.CmdGCompareImpl <em>Cmd GCompare</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.CmdGCompareImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getCmdGCompare()
     * @generated
     */
    EClass CMD_GCOMPARE = eINSTANCE.getCmdGCompare();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMD_GCOMPARE__LEFT = eINSTANCE.getCmdGCompare_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMD_GCOMPARE__RIGHT = eINSTANCE.getCmdGCompare_Right();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.CmdLCompareImpl <em>Cmd LCompare</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.CmdLCompareImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getCmdLCompare()
     * @generated
     */
    EClass CMD_LCOMPARE = eINSTANCE.getCmdLCompare();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMD_LCOMPARE__LEFT = eINSTANCE.getCmdLCompare_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMD_LCOMPARE__RIGHT = eINSTANCE.getCmdLCompare_Right();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.CmdAddImpl <em>Cmd Add</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.CmdAddImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getCmdAdd()
     * @generated
     */
    EClass CMD_ADD = eINSTANCE.getCmdAdd();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMD_ADD__LEFT = eINSTANCE.getCmdAdd_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMD_ADD__RIGHT = eINSTANCE.getCmdAdd_Right();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.CmdSubImpl <em>Cmd Sub</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.CmdSubImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getCmdSub()
     * @generated
     */
    EClass CMD_SUB = eINSTANCE.getCmdSub();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMD_SUB__LEFT = eINSTANCE.getCmdSub_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMD_SUB__RIGHT = eINSTANCE.getCmdSub_Right();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.IntLitCmdImpl <em>Int Lit Cmd</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.IntLitCmdImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getIntLitCmd()
     * @generated
     */
    EClass INT_LIT_CMD = eINSTANCE.getIntLitCmd();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_LIT_CMD__VALUE = eINSTANCE.getIntLitCmd_Value();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.GBoolTrueImpl <em>GBool True</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.GBoolTrueImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getGBoolTrue()
     * @generated
     */
    EClass GBOOL_TRUE = eINSTANCE.getGBoolTrue();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.GBoolFalseImpl <em>GBool False</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.GBoolFalseImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getGBoolFalse()
     * @generated
     */
    EClass GBOOL_FALSE = eINSTANCE.getGBoolFalse();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.StringLitImpl <em>String Lit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.StringLitImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getStringLit()
     * @generated
     */
    EClass STRING_LIT = eINSTANCE.getStringLit();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_LIT__VALUE = eINSTANCE.getStringLit_Value();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.VariableImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__VALUE = eINSTANCE.getVariable_Value();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.PortLitImpl <em>Port Lit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.PortLitImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getPortLit()
     * @generated
     */
    EClass PORT_LIT = eINSTANCE.getPortLit();

    /**
     * The meta object literal for the '<em><b>In Side</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PORT_LIT__IN_SIDE = eINSTANCE.getPortLit_InSide();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.InPortImpl <em>In Port</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.InPortImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getInPort()
     * @generated
     */
    EClass IN_PORT = eINSTANCE.getInPort();

    /**
     * The meta object literal for the '{@link fr.mleduc.gpfl.gpfl.impl.OutPortImpl <em>Out Port</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.gpfl.gpfl.impl.OutPortImpl
     * @see fr.mleduc.gpfl.gpfl.impl.GpflPackageImpl#getOutPort()
     * @generated
     */
    EClass OUT_PORT = eINSTANCE.getOutPort();

  }

} //GpflPackage
