/**
 * generated by Xtext 2.13.0
 */
package fr.mleduc.gpfl.gpfl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see fr.mleduc.gpfl.gpfl.GpflPackage
 * @generated
 */
public interface GpflFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GpflFactory eINSTANCE = fr.mleduc.gpfl.gpfl.impl.GpflFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Program</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Program</em>'.
   * @generated
   */
  Program createProgram();

  /**
   * Returns a new object of class '<em>Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Field</em>'.
   * @generated
   */
  Field createField();

  /**
   * Returns a new object of class '<em>Automata Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Automata Def</em>'.
   * @generated
   */
  AutomataDef createAutomataDef();

  /**
   * Returns a new object of class '<em>State</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State</em>'.
   * @generated
   */
  State createState();

  /**
   * Returns a new object of class '<em>Transition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Transition</em>'.
   * @generated
   */
  Transition createTransition();

  /**
   * Returns a new object of class '<em>Cond Stmt</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cond Stmt</em>'.
   * @generated
   */
  CondStmt createCondStmt();

  /**
   * Returns a new object of class '<em>Iter Stmt</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Iter Stmt</em>'.
   * @generated
   */
  IterStmt createIterStmt();

  /**
   * Returns a new object of class '<em>Interrupt Stmt</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Interrupt Stmt</em>'.
   * @generated
   */
  InterruptStmt createInterruptStmt();

  /**
   * Returns a new object of class '<em>Nop Cmd</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nop Cmd</em>'.
   * @generated
   */
  NopCmd createNopCmd();

  /**
   * Returns a new object of class '<em>Accept Cmd</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Accept Cmd</em>'.
   * @generated
   */
  AcceptCmd createAcceptCmd();

  /**
   * Returns a new object of class '<em>Drop Cmd</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Drop Cmd</em>'.
   * @generated
   */
  DropCmd createDropCmd();

  /**
   * Returns a new object of class '<em>Send Cmd</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Send Cmd</em>'.
   * @generated
   */
  SendCmd createSendCmd();

  /**
   * Returns a new object of class '<em>Alarm Cmd</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Alarm Cmd</em>'.
   * @generated
   */
  AlarmCmd createAlarmCmd();

  /**
   * Returns a new object of class '<em>Set Cmd</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Set Cmd</em>'.
   * @generated
   */
  SetCmd createSetCmd();

  /**
   * Returns a new object of class '<em>Automaton Cmd</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Automaton Cmd</em>'.
   * @generated
   */
  AutomatonCmd createAutomatonCmd();

  /**
   * Returns a new object of class '<em>Stp Cmd</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Stp Cmd</em>'.
   * @generated
   */
  StpCmd createStpCmd();

  /**
   * Returns a new object of class '<em>In Port</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>In Port</em>'.
   * @generated
   */
  InPort createInPort();

  /**
   * Returns a new object of class '<em>Out Port</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Out Port</em>'.
   * @generated
   */
  OutPort createOutPort();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  GpflPackage getGpflPackage();

} //GpflFactory
