/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.gpfl.gpfl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Out Port</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.mleduc.gpfl.gpfl.GpflPackage#getOutPort()
 * @model
 * @generated
 */
public interface OutPort extends GExpression
{
} // OutPort
