/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.fsm.ide;

import fr.mleduc.fsm.ide.AbstractFsmIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class FsmIdeModule extends AbstractFsmIdeModule {
}
