/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.fsmwithmethods.ui;

import fr.mleduc.fsmwithmethods.ui.AbstractFsmWithMethodsUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class FsmWithMethodsUiModule extends AbstractFsmWithMethodsUiModule {
  public FsmWithMethodsUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
