/**
 * generated by Xtext 2.13.0
 */
package fr.mleduc.gpfl.sequence.sequence.impl;

import fr.mleduc.gpfl.sequence.sequence.InPort;
import fr.mleduc.gpfl.sequence.sequence.SequencePackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.xtext.xbase.impl.XExpressionImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>In Port</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class InPortImpl extends XExpressionImpl implements InPort
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InPortImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SequencePackage.Literals.IN_PORT;
  }

} //InPortImpl
