/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.macros.language;

import fr.mleduc.macros.language.MacrosLangStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MacrosLangStandaloneSetup extends MacrosLangStandaloneSetupGenerated {
  public static void doSetup() {
    new MacrosLangStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
