/**
 * generated by Xtext 2.13.0
 */
package fr.mleduc.lambda.ui;

import fr.mleduc.lambda.ui.AbstractLambdaUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class LambdaUiModule extends AbstractLambdaUiModule {
  public LambdaUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
