/*
 * generated by Xtext 2.12.0
 */
package fr.mleduc.cherry.converter


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Cherry1to2StandaloneSetup extends Cherry1to2StandaloneSetupGenerated {

	def static void doSetup() {
		new Cherry1to2StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
