/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.simlang.simLang.impl;

import fr.mleduc.simlang.simLang.NopCmd;
import fr.mleduc.simlang.simLang.SimLangPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.xtext.xbase.impl.XExpressionImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Nop Cmd</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NopCmdImpl extends XExpressionImpl implements NopCmd
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NopCmdImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SimLangPackage.Literals.NOP_CMD;
  }

} //NopCmdImpl
