/*
 * generated by Xtext 2.12.0
 */
package fr.mleduc.lambdafsm.parser.antlr;

import com.google.inject.Inject;
import fr.mleduc.lambdafsm.parser.antlr.internal.InternalLambdaFsmParser;
import fr.mleduc.lambdafsm.services.LambdaFsmGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class LambdaFsmParser extends AbstractAntlrParser {

	@Inject
	private LambdaFsmGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLambdaFsmParser createParser(XtextTokenStream stream) {
		return new InternalLambdaFsmParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Lambda";
	}

	public LambdaFsmGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LambdaFsmGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
