/**
 * generated by Xtext 2.13.0
 */
package fr.mleduc.gpfl.validation;

import fr.mleduc.gpfl.validation.AbstractGpflValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GpflValidator extends AbstractGpflValidator {
}
