/*
 * generated by Xtext 2.12.0
 */
package fr.mleduc.lambda.scoping;

import fr.mleduc.gpfl.scoping.GpflScopeProvider;

public abstract class AbstractLambdaScopeProvider extends GpflScopeProvider {
}
