/*
 * generated by Xtext 2.12.0
 */
package fr.mleduc.lambdafsm.serializer;

import com.google.inject.Inject;
import fr.mleduc.fsm.fsm.Fsm;
import fr.mleduc.fsm.fsm.FsmPackage;
import fr.mleduc.fsm.fsm.State;
import fr.mleduc.fsm.fsm.Transition;
import fr.mleduc.fsm.serializer.FsmSemanticSequencer;
import fr.mleduc.lambdafsm.lambdaFsm.LambdaFsmPackage;
import fr.mleduc.lambdafsm.lambdaFsm.MethodCall;
import fr.mleduc.lambdafsm.lambdaFsm.MethodDef;
import fr.mleduc.lambdafsm.services.LambdaFsmGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class LambdaFsmSemanticSequencer extends FsmSemanticSequencer {

	@Inject
	private LambdaFsmGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == FsmPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case FsmPackage.FSM:
				sequence_Fsm(context, (Fsm) semanticObject); 
				return; 
			case FsmPackage.STATE:
				sequence_State(context, (State) semanticObject); 
				return; 
			case FsmPackage.TRANSITION:
				sequence_Transition(context, (Transition) semanticObject); 
				return; 
			}
		else if (epackage == LambdaFsmPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case LambdaFsmPackage.METHOD_CALL:
				sequence_State(context, (MethodCall) semanticObject); 
				return; 
			case LambdaFsmPackage.METHOD_DEF:
				sequence_State(context, (MethodDef) semanticObject); 
				return; 
			case LambdaFsmPackage.PARAMETER:
				sequence_Parameter(context, (fr.mleduc.lambdafsm.lambdaFsm.Parameter) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Parameter returns Parameter
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Parameter(ISerializationContext context, fr.mleduc.lambdafsm.lambdaFsm.Parameter semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, LambdaFsmPackage.Literals.PARAMETER__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LambdaFsmPackage.Literals.PARAMETER__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getParameterAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     State returns MethodCall
	 *
	 * Constraint:
	 *     (method=[MethodDef|ID] (params+=State params+=State*)?)
	 */
	protected void sequence_State(ISerializationContext context, MethodCall semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     State returns MethodDef
	 *
	 * Constraint:
	 *     (name=ID (params+=Parameter params+=Parameter*)? stmts+=State*)
	 */
	protected void sequence_State(ISerializationContext context, MethodDef semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
