/*
 * generated by Xtext 2.12.0
 */
package fr.mleduc.lambdafsm.scoping;

import fr.mleduc.fsm.scoping.FsmScopeProvider;

public abstract class AbstractLambdaFsmScopeProvider extends FsmScopeProvider {
}
