/*
 * generated by Xtext 2.12.0
 */
package fr.mleduc.lambdafsm


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LambdaFsmStandaloneSetup extends LambdaFsmStandaloneSetupGenerated {

	def static void doSetup() {
		new LambdaFsmStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
