/*
 * generated by Xtext 2.12.0
 */
package fr.mleduc.simlang.ui;

import com.google.inject.Injector;
import fr.mleduc.simlang.ui.internal.SimlangActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SimLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SimlangActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SimlangActivator.getInstance().getInjector(SimlangActivator.FR_MLEDUC_SIMLANG_SIMLANG);
	}
	
}
