/**
 * generated by Xtext 2.13.0
 */
package fr.mleduc.lambda.ui.contentassist;

import fr.mleduc.lambda.ui.contentassist.AbstractLambdaProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class LambdaProposalProvider extends AbstractLambdaProposalProvider {
}
