/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.lambdafsm;

import fr.mleduc.lambdafsm.LambdaFsmStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class LambdaFsmStandaloneSetup extends LambdaFsmStandaloneSetupGenerated {
  public static void doSetup() {
    new LambdaFsmStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
