/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.simlang.ide;

import fr.mleduc.simlang.ide.AbstractSimLangIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SimLangIdeModule extends AbstractSimLangIdeModule {
}
