/*
 * generated by Xtext 2.12.0
 */
package fr.mleduc.fsmwithmethods.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFsmWithMethodsScopeProvider extends DelegatingScopeProvider {
}
