/*
 * generated by Xtext 2.12.0
 */
package fr.mleduc.simlang.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractSimLangScopeProvider extends XbaseBatchScopeProvider {
}
