/*
 * generated by Xtext 2.12.0
 */
package fr.mleduc.gpfl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGpflScopeProvider extends DelegatingScopeProvider {
}
