/*
 * generated by Xtext 2.13.0
 */
package fr.mleduc.gpfl.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractGpflScopeProvider extends XbaseBatchScopeProvider {
}
