/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.simlang;

import fr.mleduc.simlang.AbstractSimLangRuntimeModule;
import fr.mleduc.simlang.jvmmodel.SimLangCompiler;
import fr.mleduc.simlang.typesystem.SimLangTypeComputer;
import org.eclipse.xtext.xbase.compiler.XbaseCompiler;
import org.eclipse.xtext.xbase.typesystem.computation.ITypeComputer;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SimLangRuntimeModule extends AbstractSimLangRuntimeModule {
  public Class<? extends ITypeComputer> bindITypeComputer() {
    return SimLangTypeComputer.class;
  }
  
  public Class<? extends XbaseCompiler> bindXbaseCompiler() {
    return SimLangCompiler.class;
  }
}
