/*
 * generated by Xtext 2.13.0
 */
package fr.mleduc.gpfl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class GpflUiModule extends AbstractGpflUiModule {
}
