/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.macros.language.ui.quickfix;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class MacrosLangQuickfixProvider /* implements XtextQuickfixProvider  */{
}
