/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.cherry.converter.scoping;

import fr.mleduc.cherry.converter.scoping.AbstractCherry1to2ScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class Cherry1to2ScopeProvider extends AbstractCherry1to2ScopeProvider {
}
