/**
 * generated by Xtext 2.13.0
 */
package fr.mleduc.gpfl.ui;

import fr.mleduc.gpfl.ui.AbstractGpflUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GpflUiModule extends AbstractGpflUiModule {
  public GpflUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
