/**
 * generated by Xtext 2.13.0
 */
package fr.mleduc.gpfl.ide;

import fr.mleduc.gpfl.ide.AbstractGpflIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GpflIdeModule extends AbstractGpflIdeModule {
}
