/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.simlang.ui.contentassist;

import fr.mleduc.simlang.ui.contentassist.AbstractSimLangProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SimLangProposalProvider extends AbstractSimLangProposalProvider {
}
