/**
 * generated by Xtext 2.13.0
 */
package fr.mleduc.gpfl.sequence.ui.contentassist;

import fr.mleduc.gpfl.sequence.ui.contentassist.AbstractSequenceProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SequenceProposalProvider extends AbstractSequenceProposalProvider {
}
