/*
 * generated by Xtext 2.12.0
 */
package fr.mleduc.lambdafsm.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class LambdaFsmUiModule extends AbstractLambdaFsmUiModule {
}
