/*
 * generated by Xtext 2.12.0
 */
package fr.mleduc.cherry.converter.parser.antlr;

import com.google.inject.Inject;
import fr.mleduc.cherry.converter.parser.antlr.internal.InternalCherry1to2Parser;
import fr.mleduc.cherry.converter.services.Cherry1to2GrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class Cherry1to2Parser extends AbstractAntlrParser {

	@Inject
	private Cherry1to2GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCherry1to2Parser createParser(XtextTokenStream stream) {
		return new InternalCherry1to2Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public Cherry1to2GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Cherry1to2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
