/**
 * generated by Xtext 2.12.0
 */
package fr.mleduc.fsm;

import fr.mleduc.fsm.AbstractFsmRuntimeModule;
import fr.mleduc.fsm.interpreter.FsmInterpreter;
import fr.mleduc.fsm.interpreter.IFsmInterpreter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class FsmRuntimeModule extends AbstractFsmRuntimeModule {
  public Class<? extends IFsmInterpreter> bindIFsmInterpreter() {
    return FsmInterpreter.class;
  }
}
